# Generated by Django 4.1.7 on 2023-03-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_content_news_description_news_detail_news_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
